[package]
name = "egui-graph-bhv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23"
egui_graphs = { version = "0"}
petgraph = { version = "0.6"}
bhv-async = { path = "../"}
